# server
server:
  port: 10001


# jdbc
spring:
  datasource: ${{ secrets.RDS_ADDRESS }}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:  ${{ secrets.RDS_USERNAME }}
    password: ${{ secrets.RDS_PASSWORD }}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  # jpa
  jpa:
    hibernate:
      ddl-auto: none

    # jpa format
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # log
  output:
    ansi:
      enabled: always
